services:

  reddit_collector:
    build: ./reddit_collector/
    volumes:
      - ./reddit_collector:/app
    depends_on:
      - mongodb
    env_file:
      - .env

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    env_file:
      - .env

  etl_job:
    build: ./etl_job/
    volumes:
      - ./etl_job:/app
    depends_on:
      - mongodb
      - postgresdb
    env_file:
      - .env

  postgresdb:
    image: postgres
    ports:
      - 5555:5432
    env_file:
      - .env

  slackbot:
    build: ./slack_bot/
    volumes:
      - ./slack_bot:/app
    depends_on:
      - postgresdb
    env_file:
      - .env