services:

  reddit_collector:
    build: ./reddit_collector/
    volumes:
      - ./reddit_collector:/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - 27017:27017

  #etl_job:
  #  build: ./etl_job/
  #  volumes:
  #    - ./etl_job:/app
  #  depends_on:
  #    - postgres

  #postgres:
  #  image: postgres
  #  ports:
  #    - 

  # 5th container
  #slackbot:
  # build: